fix: add new routes + change controllers
lmtsufape/vida-agroecologica-ecommerce-api pull request #109
Opened 2023-10-17 18:47 UTC by ellenmariadev

2023-10-17 19:39 UTC, Rener1 commented on app/Http/Controllers/UserController.php
> +        $query->whereIn('nome', ['presidente']);
Como o array possui somente um valor, a cláusula whereIn pode ser substituido por where comum.

2023-10-17 19:46 UTC, Rener1 commented on app/Http/Controllers/Web/AssociacaoController.php
> +    $associacao = Associacao::where('id', $id)->with('presidentes', 'contato')->first();
Acredito que um findOrFail ou um find normal simplificaria tanto o código como a query.

2023-10-18 17:37 UTC, Rener1 commented on app/Http/Controllers/Web/OrganizacaoControleSocialController.php
> +        $ocs = OrganizacaoControleSocial::with('associacao', 'endereco', 'contato', 'endereco.bairro')->findOrFail($id);
Pode ser otimizado usando o método findOrFail primeiro e em seguida o método load() para puxar o restante das tabelas.

2023-10-18 17:44 UTC, Rener1 commented on app/Models/Associacao.php
O que aconteceu com a tabela de contatos?

2023-10-18 17:44 UTC, Rener1 approved these changes

2023-10-18 18:28 UTC, ellenmariadev commented on app/Models/Associacao.php
Não mexi não 🥶

2023-11-15 15:27 UTC, Rener1 requested changes
@ellenmariadev @jvictorcordeiro vejam o que precisa ser modificado e vão falando comigo o que precisar.

2023-11-15 15:27 UTC, Rener1 commented on app/Models/User.php
> +    public function associacoesSecretario()
Alterar o nome do método para deixar mais clara a relação. Ex: associacoesGerenciadas.

2023-11-15 15:27 UTC, Rener1 commented on app/Models/User.php
> +    public function oscAgricultores()
Novamente a relação many to many.
Vamos lá:

1. Acredito que era para ser ocsAgricultores.
2. Se a relação é entre usuário e ocs, no modelo do usuário coloca-se o nome do método como apenas ocs.
3. Essa relação já existe, é a "organizacao" mais em baixo.
4. A método indica uma relação com o ocs mas a classe que está sendo usada é do model de Associacao.
5. Ao criar uma tabela intermediária, por convenção colocamos os nomes das classes em ordem alfabetica e no singular. Ficaria agricultor_ocs, ou agricultor_organizacao.

2023-11-15 15:27 UTC, Rener1 commented on database/migrations/2023_11_02_145023_create_ocs_agricultores_table.php
Rever essa relação many to many, não lembro de modificações solicitadas aqui.

2023-11-15 15:27 UTC, Rener1 commented on routes/api.php
> +    Route::delete('/users/{id}', 'destroy');
Rota já existente, `Route::apiResource('/users', ApiUserController::class)->except('store')->middleware('auth:sanctum');` já cria ela e várias outras.

2023-11-15 15:27 UTC, Rener1 commented on routes/api.php
> + Route::delete('/associacoes/{id}', [AssociacaoController::class, 'destroy']);
Pode ser simplificado usando Route::apiResource() que já inclui todas as rotas de api.

2023-11-15 15:27 UTC, Rener1 commented on resources/js/bootstrap.js
Para que serve?

2023-11-15 15:58 UTC, ellenmariadev commented on app/Http/Middleware/VerifyCsrfToken.php
> +        '*',
De fato tem remover esse '*' antes de colocar em produção e arrumar um jeito de passar a verificação CSRF do Laravel para o React

```php
    <meta name="csrf-token" content="{{ csrf_token() }}">
```
Erro no React quando remove "*":
 
![image](https://github.com/lmtsufape/vida-agroecologica-ecommerce-api/assets/99571291/ceee7b94-73b2-497f-bbd5-727be456f8aa)

2023-11-15 17:25 UTC, jvictorcordeiro commented on app/Models/OrganizacaoControleSocial.php
> +        return $this->belongsToMany(User::class, 'ocs_agricultores', 'organizacoes_controle_social_id', 'agricultor_id')->withTimestamps();
Eu acredito que sim, não?

2023-11-23 21:09 UTC, Rener1 requested changes

2023-11-23 21:09 UTC, Rener1 commented on app/Http/Middleware/VerifyCsrfToken.php
> +        '*',
Recomendo não subir da forma que está para não acabar esquecendo de remover posteriormente.

2024-02-05 16:30 UTC, merged